# DEPRECATED: El archivo docker-compose.yml fue dejado en modo deprecated.
#
# Hermes Purge: esta infraestructura local ha sido deprecada.
# Para mantener historial y trazabilidad se reemplaza el contenido por una nota.

# Si necesitas restaurar la infraestructura local, revisa los commits anteriores
# o extrae la versión desde el historial de Git.

# Nota: El pipeline de CI/CD se encarga ahora del despliegue en Railway y Vercel.
      retries: 12
      start_period: 10s
    networks:
      - praevisio_net

volumes:
  praevisio_db_data:
  neo4j_data:
  neo4j_logs:

networks:
  praevisio_net:
    driver: bridge
