version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: praevisio_backend
    ports:
      - '4000:4000'
    environment:
      PRAEVISIO_BEARER_TOKEN: ${PRAEVISIO_BEARER_TOKEN:-demo-token}
      DATABASE_URL: file:./prisma/dev.db
    volumes:
      - ./server/dev.db:/app/app/prisma/dev.db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/api/platform-status -H \"Authorization: Bearer ${PRAEVISIO_BEARER_TOKEN:-demo-token}\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: 'http://backend:4000'
    container_name: praevisio_frontend
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: praevisio_network
