#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const args = process.argv.slice(2);
const status = args[0] || 'unknown';
let details = {};
try { details = args[1] ? JSON.parse(args[1]) : {}; } catch(e){ details = { raw: args[1] } }

const ts = new Date().toISOString().replace(/[:.]/g, '-');
const fname = `IMMORTAL_EVOLUTION_REPORT_${ts}.md`;
const outPath = path.join(process.cwd(), fname);

const content = `# IMMORTAL EVOLUTION REPORT - ${new Date().toISOString()}

- status: ${status}
- mission: ${details.mission || 'n/a'}
- branch: ${details.branch || 'n/a'}
- timestamp: ${details.timestamp || new Date().toISOString()}

## Test Result

${status === 'success' ? 'All tests passed ✅' : 'Tests failed ❌'}

## Notes

- This report was generated by scripts/generate_report.js as part of the Aion cycle.
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`[Aion] Report generated: ${outPath}`);
