name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  issues: write

jobs:
  lint_and_test_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          npm ci
          cd server && npm ci
      - name: Run lint
        run: npm run lint --if-present || echo "No lint script"
      - name: Run unit tests
        run: npm test || echo "Unit tests may be absent"

  e2e:
    needs: lint_and_test_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Compose
        uses: docker/setup-docker@v2
      - name: Build images with docker-compose
        run: docker compose build --progress=plain
      - name: Start services
        run: docker compose up -d
      - name: Wait for backend health (uses secret)
        env:
          PRAEVISIO_BEARER_TOKEN: ${{ secrets.PRAEVISIO_BEARER_TOKEN }}
        run: |
          TOKEN=${PRAEVISIO_BEARER_TOKEN:-demo-token}
          for i in {1..30}; do
            if curl -sS http://localhost:4000/api/platform-status -H "Authorization: Bearer $TOKEN" >/dev/null; then
              echo "Backend is up"; exit 0
            fi
            echo "Waiting for backend... ($i/30)"; sleep 2
          done
          echo "Backend failed to become healthy"; exit 1
      - name: Install dev deps + Playwright
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          NODE_ENV: test
          PRAEVISIO_BEARER_TOKEN: ${{ secrets.PRAEVISIO_BEARER_TOKEN }}
        run: npx playwright test --config=playwright.config.ts --reporter=json --output=test-results
      - name: Detect flaky tests
        if: always()
        run: node scripts/detect-flaky-tests.js
      - name: Tear down
        if: always()
        run: docker compose down --volumes || true
