name: Create Release with Artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release (e.g. v1.0.0)'
        required: true
        default: 'transplant-$(date +%s)'
      name:
        description: 'Release name'
        required: false
        default: 'Transplant Release'
      body:
        description: 'Release body / notes'
        required: false
        default: 'Automated release with transplant artifacts.'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.name }}
          body: ${{ github.event.inputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist artifact (if present)
        if: always()
        uses: softprops/action-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/dist_release_*.tar.gz
          asset_name: dist_release.tar.gz
          asset_content_type: application/gzip

      - name: Upload backup artifact (if present)
        if: always()
        uses: softprops/action-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/backup_frontend_*.tar.gz
          asset_name: backup_frontend.tar.gz
          asset_content_type: application/gzip
