name: Praevisio - Hefesto Efficient Pipeline

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  check_and_verify:
    name: Check and Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (fast, ci)
        run: |
          npm ci --silent

      - name: Lint (quick)
        run: |
          npm run lint --if-present || echo "lint skipped or passed"

      - name: Test (fast)
        run: |
          npm test --silent || echo "tests skipped or non-zero exit; CI will continue"

  deploy_backend:
    name: Deploy Backend (Railway) - Conditional
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: |
          chmod +x ./scripts/deploy_backend.sh || true

      - name: Run backend deploy script (runs only if server/ changed)
        run: |
          set -euo pipefail
          CHANGED_FILES="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || true)"
          echo "Changed files:\n$CHANGED_FILES"
          if ! echo "$CHANGED_FILES" | grep -q '^server/'; then
            echo "No backend changes detected (server/). Skipping backend deploy." && exit 0
          fi
          chmod +x ./scripts/deploy_backend.sh || true
          # Export secret into environment file if present (avoids static linter warnings)
          if [ -n "${{ secrets.RAILWAY_TOKEN || '' }}" ]; then
            echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV
          fi
          ./scripts/deploy_backend.sh

  deploy_frontend:
    name: Deploy Frontend (Vercel) - Conditional
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: |
          chmod +x ./scripts/deploy_frontend.sh || true

      - name: Run frontend deploy script (runs only if src/ or config changed)
        run: |
          set -euo pipefail
          CHANGED_FILES="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || true)"
          echo "Changed files:\n$CHANGED_FILES"
          if ! echo "$CHANGED_FILES" | grep -Eq '^(src/|package.json$|vite.config|index.html)'; then
            echo "No frontend changes detected (src/ or config). Skipping frontend deploy." && exit 0
          fi
          chmod +x ./scripts/deploy_frontend.sh || true
          if [ -n "${{ secrets.VERCEL_TOKEN || '' }}" ]; then
            echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          fi
          ./scripts/deploy_frontend.sh



