name: Multi-Arch Build & Sim Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (simulated)
        run: |
          echo "Simulating buildx build for linux/amd64,linux/arm64"
          echo "docker buildx build --platform linux/amd64,linux/arm64 -t example/multi:latest . --push"
